spring:
  application:
    name: apiMensagem
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  mensageria:
    rabbit:
      exchange: fretes.exchange
      queue: fretes.eventos.queue
      routing-key: fretes.eventos
    websocket:
      topic-fretes: /topic/fretes
